# Generated by Django 5.2.8 on 2025-12-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_systemupdate_target_type_systemupdate_target_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemupdate',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='موعد التحديث'),
        ),
    ]
